language: python
python:
  - 2.7
  - 3.6

os:
  - linux

sudo: required
services: docker

env:
  global:
    - ERT_SHOW_BACKTRACE=1
    - MB_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
    - VERSION=$(echo $TRAVIS_TAG | sed s/v//)
  matrix:
    - TEST_SUITE="-LE SLOW"  # Run all tests not labeled as slow
    - TEST_SUITE="-L SLOW_1" # Run all tests labeled as SLOW in group 1
    - TEST_SUITE="-L SLOW_2" # Run all tests labeled as SLOW in group 2

matrix:
  fast_finish: true
  include:
    - os: osx
      language: generic
      python: 2.7
      env:
        - MB_PYTHON_VERSION=2.7
        - TEST_SUITE=""
    - os: osx
      language: generic
      python: 3.6
      env:
        - MB_PYTHON_VERSION=3.6
        - TEST_SUITE=""

addons:
  apt:
    packages:
    - liblapack-dev

before_install:
  - git clone https://github.com/matthew-brett/multibuild.git
  - unset -f pushd
  - unset -f popd
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - pip install -r requirements.txt

script:
  - mkdir build
  - pushd build
  - cmake .. -DBUILD_TESTS=ON
             -DENABLE_PYTHON=ON
             -DINSTALL_CWRAP=OFF
             -DBUILD_APPLICATIONS=ON
             -DINSTALL_ERT_LEGACY=ON
             -DERT_USE_OPENMP=ON
             -DCMAKE_C_FLAGS='-Werror=all'
             -DCMAKE_CXX_FLAGS='-Werror -Wno-unused-result'
  - make
  - sudo make install
  - which python
  - export PYTHONPATH="/usr/local/lib/python$MB_PYTHON_VERSION/site-packages:/usr/local/lib/python$MB_PYTHON_VERSION/dist-packages:$PYTHONPATH"
  - python -c "import sys; print('\n'.join(sys.path))"
  - set -e; python -c "import ecl"; set +e
  - ctest --output-on-failure $TEST_SUITE
  - popd

deploy:
    - provider: pypi # source distribution (done linux python 2.7 only)
      skip_cleanup: true
      skip_upload_docs: true
      user: xjules
      distributions: sdist bdist_wheel
      password:
        secure: qqN8VyzV4YbdUofCoo65KWO+87+1PcOHpKp4JKHXwZ9uandFjwdvuTYiZ/XR4yk0rLa28qpa9iUfk4iWkC8zfFcKWuJ/9I45I8kbhvM6tD2UtCGfmR3AzNceEC1/9OBCpnBU8MTTrY9SNULeqanOPPQlvy8X54lAdEbXHOzlNYheAG+htE8PSUO0FTOaYrDAfR+slRBSQ8OqDuhi/MNo87az85jmX9ONbkuaOyoc13QoVlQ+Yzfw0eBQjzg+C+59JGNp18Fpoyp4NDSYyE1LRUbNMr1ud7id8AIg9tMOc1pjYk8FBIIT2hnSKh1BdQm2lLvQRQWIznsspDMrey/AXOf8knPqR1TjVxVTEbjdvDtQHibIA2vAyX6s4vYBbZfL/jelv11IWS02lgjzJCKXzvkJUsSymmVCHF//zOOjJfZoEJOIzPH2jwwd1iWuaeE4C6JIpU2QV3x8gsNPJjesJgAr7je25ciDOIlyeNfoubIl713Q3BKyAiQBk3d6bpd0o8p57rOoWegoYSe7sfPGyrM88UlbGvmM7Rj+DJHl7jMy711BIf6R51lJguwVgzRg6r+jRdAHLKEpZZ7oc33BVEo4ZowU2awywepo/IVNTFi6X2S24oZ/ZalRLKM+W3yRPRZXifgfqW2Ssk0qK+7SlBmpDYteXuThyFjpBUWilbA=
      on:
        condition: "$MB_PYTHON_VERSION = 2.7" AND "$TEST_SUITE = -LE SLOW"
        tags: true
