language: python

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

matrix:
    fast_finish: true
    exclude:
        - os: osx
        - os: linux
          compiler: clang
    include:
        - os: osx
          osx_image: xcode7.3
          compiler: clang
          env: MB_PYTHON_VERSION=2.7

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - liblapack-dev
            - zlib1g-dev
            - valgrind

services: docker
sudo: required

env:
    global:
        - ERT_SHOW_BACKTRACE=1
        - UNICODE_WIDTH=32
        - PLAT=x86_64

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update && brew install cppcheck;
        if [[ -n "${MB_PYTHON_VERSION+1}" ]]; then
            prefix=`python-config --prefix`;
            pypath=$prefix/lib/libpython$MB_PYTHON_VERSION.dylib;
            pylib="-DPYTHON_LIBRARY=$pypath";
        fi
      fi
    - pip install requests

before_script:
    - wget https://raw.githubusercontent.com/Statoil/ert/master/travis/build_total.py
    - pip install -r requirements.txt
    - mkdir build
    - pushd build
    - cmake -DBUILD_TESTS=ON
            -DBUILD_PYTHON=ON
            -DERT_BUILD_CXX=ON
            -DBUILD_APPLICATIONS=ON
            -DBUILD_ECL_SUMMARY=ON
            -DCMAKE_INSTALL_PREFIX=install
            -DINSTALL_ERT_LEGACY=ON
            ..
    - popd

script:
    - pushd build
    - make
    - make install
    - cmake .. -DINSTALL_ERT_LEGACY=OFF
    - make
    - cat python/setup.py
    - popd
    - BUILD_COMMANDS=build_bdist_wheel build_wheel build/python
    - install_run $PLAT
    - mv wheelhouse build/python/dist
    - python build_total.py ecl

before_deploy:
    - pushd build/python

after_deploy:
    - popd

deploy:
    - provider: pypi # upload built wheels
      skip_cleanup: true
      skip_upload_docs: true
      user: statoil-travis
      distributions: sdist build
      password:
        secure: YlsAgk9t2Lc5wfCv2aMeOmB10HLoqcRBiYVQ3oGwsaEj6OP09iCEs+lvfyPU2wDVDrYmbbom8icUShFbue1B7qwUV9liVXRXvH80RAmVaWJaRhQ/FaiKWmP9hKnACutjEOc2QqTPcZvRRJb7Tr3RlMz1tcqJKVW47oil/TA5E3XZ9EIreX2JuUvcVeJ59aQ7X+EAu4NQBYXgqTI4rnpLncojt0cuBI5OdQ4+VvEmSuZY2CS/UX3ZsWuaC7REVn3NPK/a40ka47OnbPXkZJRJCa+06vukC9SProuX0d5ck93UCJxOBuSf8876Tx9QvpPMNknDVKmxf1ZBfSsZY74LzVY2PAbImvinaPfGodIXC7zGp6uxVObf6Ku3UJX66ZfRXLsQhK5uvEpZOyGAqyk8UEffXconqYKwVzfJKHVpusLYU3VmrRfyy+Xg/hBfRYJI/sePllm+bvNzzJuiWN3Pky3t0XZxQ09mVXgkbjvmjhZfewMawe833DcfIxD8h6EMHf2Zas6swohbYUPdsMePcBZy+CV9+zi4L39EDu99lYT2Li0oufC9q5ukDMWgnKSXuGMBGv/+vn//b6nMgyRfGIqV3GhAvACbODE+6TAHmcUJLSTBvQNrv/Oc7mBiOFJw3hGYkNsIvJ6IOHffY4NspoTSjPpXxn/+/fhHxyDwoyg=
      on:
        tags: true
        branch: master
